### PR TITLE
Add support for static class methods

### PR DESCRIPTION
**Pull request by ilkkao**
Support static class methods

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static

### CODE REVIEW

**Comment by ilkkao** [comment]
Fixes https://github.com/leebyron/async-to-gen/issues/4

**Comment by leebyron** [comment]
Thanks for the report and the quick fix. Unfortunately this approach could be broken by odd white space

**Comment by ilkkao** [comment]
Right, I could use a regex to do the same modification. 

I haven't used babylon before. If there's a better way to do it, maybe somebody else can have a stab.

**Comment by leebyron** [comment]
See: 94cfb135ad26d21b5a55de92d797329225191730 I recycled your test case :)

**Comment by ilkkao** [comment]
Nice!

**Pull request closed without merging**
